services:
  ### APPLICATION PART
  runner:
    image: maeddes/spanimals-runner:${VERSION}
    build:
      context: ./runner
    ports:
      - "5003:5003"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT_GRPC}
      - OTEL_RESOURCE_ATTRIBUTES=service.name=runner
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_PYTHON_LOG_AUTO_INSTRUMENTATION=true
      - OTEL_PYTHON_LOG_CORRELATION=true

  fact-generator:
    image: maeddes/spanimals-fact-generator:${VERSION}
    build:
      context: ./fact-generator
    ports:
      - "5001:5001"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT_GRPC}
      - OTEL_RESOURCE_ATTRIBUTES=service.name=fact-generator
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_PYTHON_LOG_AUTO_INSTRUMENTATION=true
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  image-generator:
    #image: maeddes/spanimals-image-generator:${VERSION}
    build:
      context: ./image-generator
    ports:
      - "5002:5002"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT_GRPC}
      - OTEL_RESOURCE_ATTRIBUTES=service.name=image-generator
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_PYTHON_LOG_AUTO_INSTRUMENTATION=true
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOG_LEVEL=info
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  image-database:
    image: maeddes/spanimals-image-database:${VERSION}
    build:
      context: ./image-database
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_RESOURCE_ATTRIBUTES=service.name=image-database
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=grpc
      - OTEL_METRICS_EXPORTER=otlp,logging-otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_JAVAAGENT_ENABLED=true
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
      - otelcol

  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
    ports:
      - "5432:5432"

  ### OTEL PART

  otelcol:
    image: otel/opentelemetry-collector-contrib
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./config/otel-collector-config-alt.yml:/etc/otel-collector-config.yml
    command: ["--config=/etc/otel-collector-config.yml"]


  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686" # Jaeger UI
   
  prometheus:
    image: quay.io/prometheus/prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.enable-otlp-receiver
      - --web.enable-remote-write-receiver
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus-config.yaml
    restart: unless-stopped
    ports:
      - "9090:9090"

  # opensearch:
  #   image: opensearchproject/opensearch:2
  #   container_name: opensearch
  #   environment:
  #     discovery.type: single-node
  #     plugins.security.disabled: "true"
  #     OPENSEARCH_INITIAL_ADMIN_PASSWORD: "admin"
  #     OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"
  #     - "9600:9600"

  # opensearch-dashboards:
  #   image: opensearchproject/opensearch-dashboards:2
  #   container_name: opensearch-dashboards
  #   environment:
  #     OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
  #     DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - opensearch